gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is Oak.\p"
	.string "People call me the Pokémon\n"
	.string "Professor.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as Pokémon.\p"
	.string "People and Pokémon live together,\n"
	.string "by supporting each other.\p"
	.string "Some people play with Pokémon,\n"
	.string "some battle with them. \p"
	.string "But we don't know everything about\n"
	.string "Pokémon yet. \p"
	.string "There are still many mysteries\n"
	.string "to solve. That's why I study\l"
	.string "Pokémon every day.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_Difficulty::
	.string "Aha…\p"
	.string "And… How do you think this\n"
	.string "adventure is going to be?$"

gText_Birch_LockDifficulty::
	.string "If you need to change the Difficulty\n"
	.string "you can open the Options Menu and\l"
	.string "change it from there.\p"
	.string "You can also lock it, if you want.\n"
	.string "Do you want to lock the\l"
	.string "chosen Difficulty?\p"
	.string "This cannot be changed later.$"

gText_Birch_ChallengeEasy::
	.string "Oh, is that so?\p"
    .string "Easy Mode lowers the challenge by\n"
    .string "scaling down enemy and wild Pokémon.\p"
    .string "Your Pokémon also gain 30% more Exp.\p"
    .string "You can change Difficulty anytime\n"
    .string "from the Options Menu, unless you\l"
    .string "choose to lock the Difficulty.\p"
	.string "All right, with that clear…\n"
	.string "Do you expect any Challenge\l"
	.string "in your journey?$"

gText_Birch_ChallengeNormal::
	.string "Oh, is that so?\p"
    .string "Normal Mode keeps the same\n"
    .string "difficulty as vanilla Heart & Soul.\l"
	.string "There are no changes, at all.\p"
    .string "You can change Difficulty anytime\n"
    .string "from the Options Menu, unless you\l"
    .string "choose to lock the Difficulty.\p"
	.string "All right, with that clear…\n"
	.string "Do you expect any Challenge\l"
	.string "in your journey?$"

gText_Birch_ChallengeHard::
    .string "Oh, is that so?\p"
    .string "Hard Mode is more challenging than\n"
    .string "Normal Mode.\p"
    .string "It is not meant to replace dedicated\n"
    .string "Difficulty Hackroms, but uses simple\l"
    .string "mechanics to raise the difficulty.\l"
    .string "This Mode includes:\p"
    .string "Pokémon gain -20% Experience.\p"
    .string "Enemy and wild Pokémon level scale\n"
    .string "with your Badges.\p"
	.string "All Badge Boosts removed.\p"
	.string "You can't use more than 4 items\n"
	.string "in battle.\p"
    .string "Damage taken rises as Badges are\n"
    .string "earned.\p"
    .string "All legendaries are banned in the BF.\p"
    .string "You can change Difficulty anytime\n"
    .string "from the Options Menu, unless you\l"
    .string "choose to lock the Difficulty.\p"
    .string "Options exist to Unban legendaries\n"
    .string "and restore normal Experience gain.\p"
	.string "All right, with that clear…\n"
	.string "Do you expect any Challenge\l"
	.string "in your journey?$"

gText_Birch_Challenge::
	.string "Oh, is that so?\p"
	.string "All right, with that clear…\n"
	.string "Do you expect any Challenges\l"
	.string "in your journey?\p"
	.string "And what's your name?$"

gText_Birch_WhatsYourName::
	.string "Now, what did you say your name.\n"
	.string "was?$"

gText_Birch_SoItsPlayer::
	.string "Oh! So you're {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "{PLAYER}{KUN}, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "You'll face fun times and tough\n"
	.string "challenges.\p"
	.string "A world of dreams and adventures\n"
	.string "with Pokémon awaits! Let's go!\p"
	.string "I'll be seeing you later!\p"
	.string "$"

gText_Birch_ChallengeSelected::
	.string "Great! Remember that you can\n"
	.string "check which Challenges are\l"
	.string "active using a PC.$"
